export interface HeroDefinition {
  id: string;
  name: string;
  emoji: string;
  baseCost: number;
  baseDPS: number;
  description: string;
  color: number;
  rarity: string;
}

export const HERO_DATA: HeroDefinition[] = [
  {
    id: 'baby_gronk',
    name: 'Baby Gronk',
    emoji: '👶',
    baseCost: 10,
    baseDPS: 1,
    description: 'A tiny but determined brainrot warrior',
    color: 0x4a90d9,
    rarity: 'Common',
  },
  {
    id: 'skibidi_toilet',
    name: 'Skibidi Toilet',
    emoji: '🚽',
    baseCost: 100,
    baseDPS: 5,
    description: 'Emerging from porcelain to fight for your click',
    color: 0x7ed321,
    rarity: 'Common',
  },
  {
    id: 'rizz_god',
    name: 'Rizz God',
    emoji: '😎',
    baseCost: 1000,
    baseDPS: 25,
    description: 'Unmatched charisma dealing devastating damage',
    color: 0xf5a623,
    rarity: 'Common',
  },
  {
    id: 'sigma_wolf',
    name: 'Sigma Wolf',
    emoji: '🐺',
    baseCost: 10000,
    baseDPS: 100,
    description: 'Lone sigma grinding DPS in the shadows',
    color: 0x9b59b6,
    rarity: 'Rare',
  },
  {
    id: 'ohio_final_boss',
    name: 'Ohio Final Boss',
    emoji: '🏴',
    baseCost: 100000,
    baseDPS: 400,
    description: 'The ultimate manifestation of Ohio chaos',
    color: 0xe74c3c,
    rarity: 'Rare',
  },
  {
    id: 'fanum_tax_collector',
    name: 'Fanum Tax Collector',
    emoji: '💸',
    baseCost: 1_000_000,
    baseDPS: 1500,
    rarity: 'Rare',
    description: 'Steals HP from enemies to fuel your grind',
    color: 0x27ae60,
  },
  {
    id: 'gyatt_guardian',
    name: 'Gyatt Guardian',
    emoji: '🛡️',
    baseCost: 10_000_000,
    baseDPS: 6000,
    rarity: 'Epic',
    description: 'Shield + devastating DPS combo',
    color: 0x2980b9,
  },
  {
    id: 'mewing_master',
    name: 'Mewing Master',
    emoji: '🧘',
    baseCost: 100_000_000,
    baseDPS: 25000,
    rarity: 'Epic',
    description: 'Silent but deadly DPS machine',
    color: 0x8e44ad,
  },
  {
    id: 'kai_cenat_clone',
    name: 'Kai Cenat Clone',
    emoji: '😤',
    baseCost: 1_000_000_000,
    baseDPS: 100000,
    rarity: 'Epic',
    description: 'Rage multiplier for your whole squad',
    color: 0xd35400,
  },
  {
    id: 'duke_dennis',
    name: 'Duke Dennis',
    emoji: '👑',
    baseCost: 10_000_000_000,
    baseDPS: 500000,
    rarity: 'Legendary',
    description: 'Rizz aura that buffs all heroes',
    color: 0xf39c12,
  },
  {
    id: 'cameraman_elite',
    name: 'Cameraman Elite',
    emoji: '📹',
    baseCost: 100_000_000_000,
    baseDPS: 2_000_000,
    rarity: 'Legendary',
    description: 'Anti-Skibidi specialist',
    color: 0x1abc9c,
  },
  {
    id: 'livvy_dunne',
    name: 'Livvy Dunne',
    emoji: '🤸',
    baseCost: 1_000_000_000_000,
    baseDPS: 10_000_000,
    rarity: 'Legendary',
    description: 'Gymnastic crits are off the charts',
    color: 0xe91e8c,
  },
  {
    id: 'ishowspeed',
    name: 'IShowSpeed',
    emoji: '⚡',
    baseCost: 10_000_000_000_000,
    baseDPS: 50_000_000,
    rarity: 'Mythic',
    description: 'SPEED boost for the entire team',
    color: 0xff5722,
  },
  {
    id: 'quandale_dingle',
    name: 'Quandale Dingle',
    emoji: '😈',
    baseCost: 100_000_000_000_000,
    baseDPS: 500_000_000,
    rarity: 'Mythic',
    description: 'Chaos damage that cannot be predicted',
    color: 0x9c27b0,
  },
  {
    id: 'brainrot_king',
    name: 'The Brainrot King',
    emoji: '🧠',
    baseCost: 1_000_000_000_000_000,
    baseDPS: 5_000_000_000,
    rarity: 'Mythic',
    description: 'Ultimate DPS — the final form',
    color: 0xff0000,
  },
];
